language: python
dist: xenial
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

services: xvfb
addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  # Install version specific packages for 2.7 and 3.5
  - pip install 'pandas<0.25'
  - pip install xarray
  - pip install matplotlib
  # Install pysatCDF and dump output
  - pip install pysatCDF >/dev/null
  # Prepare modified pysat install
  - pip install numpy
  - cd ..
  - echo 'cloning pysat'
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - echo 'installing pysat'
  - cd ./pysat
  - git checkout develop-3
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install >/dev/null
  - cd ../pysatSeasons

install:
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0

script:
  - pytest -vs --cov=pysatSeasons/

after_success:
  - coveralls
