language: python
dist: xenial
jobs:
  include:
    - name: Minimum NEP 029 versions
      python: 3.6
      env: NUMPY_VER=1.15
    # Versions with latest numpy
    - python: 3.6
    - python: 3.7
    - python: 3.8

services: xvfb
addons:
  apt:
    packages:
    - gfortran

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas xarray requests beautifulsoup4 lxml netCDF4 nose pytest-cov pytest-ordering coveralls future
  - conda activate test-environment
  # check for custom version of numpy
  - if [ -z ${NUMPY_VER} ]; then
      echo 'Using latest numpy';
    else
      conda install -q numpy==$NUMPY_VER;
    fi
  # Dependencies not available through conda, install through pip
  - pip install PyForecastTools
  - pip install pysatCDF >/dev/null
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install
  # install pysatSeasons
  - cd ../pysatSeasons
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0

script:
  - pytest -vs --cov=pysatSeasons/

after_success:
  - coveralls
