language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7

services: xvfb

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib

install:
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0
  - if [[ $TRAVIS_PYTHON_VERSION < "3.0" ]]; then
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - pytest -vs --cov=pysatSeasons/

after_success:
  - coveralls
